# Site settings
title: Adventure Photo
email: paul.negoescu@gmail.com
description: "Adventurous photography happening in exotic places all over the world. A photography blog and a portfolio of passionat people."
baseurl: ""
url: "http://yourdomain.com"


# Build settings
markdown: kramdown
permalink: pretty

#Other
highlighter: rouge
encoding: utf-8
sass:
    sass_dir: _sass
    style: compressed